version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: periodic-mongodb
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --noauth
    networks:
      - periodic-network

  api:
    build: .
    container_name: periodic-api
    ports:
      - "4567:4567"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    depends_on:
      - mongodb
    networks:
      - periodic-network

volumes:
  mongodb_data:

networks:
  periodic-network:
    driver: bridge